[package]
name = "compression"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
viz = { workspace = true, features = ["compression"] }

tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
