[package]
name = "session"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
viz = { workspace = true, features = ["session"] }

tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

sessions = { version = "0.5.0", features = ["memory"] }
nano-id = "0.3"
