[package]
name = "websocket-chat"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
viz = { workspace = true, features = ["websocket"] }

tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
futures-util.workspace = true
